name:                welcome-bot
version:             0.1.0.0
github:              "jams2/welcome-bot"
license:             BSD3
author:              "Joshua Munn"
maintainer:          "public@elysee-munn.family"
copyright:           "2021 Joshua Munn"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jams2/welcome-bot#readme>

dependencies:
- base >= 4.7 && < 5
- scotty
- aeson
- aeson-casing
- text
- yaml
- optparse-applicative
- directory
- transformers
- http-types
- wai-extra

library:
  source-dirs: src

executables:
  welcome-bot:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - welcome-bot

tests:
  welcome-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - welcome-bot
